name: "SonarSource LT release"
description: "Release SonarSource LT projects"
author: "Thomas Vérin"
outputs:
  releasability:
    description: "Output from releasability gcp function checks"
  release:
    description: "Output from release gcp function checks"
runs:
  using: "docker"
  image: "Dockerfile"
