name: "SonarSource LT release"
description: "Release SonarSource LT projects"
author: "Thomas Vérin"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
