name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        # Put your action repo here
        uses: SonarSource/gh-action_LT_release@czurn/releasability

      - name: Check outputs
        run: |
          echo "${{ steps.selftest.outputs.releasability }}"
          echo "${{ steps.selftest.outputs.release }}"
